version: '3'
services:
  mysql-server:
    image: mysql:5.7.18
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: perf
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - ./mysql_data:/docker-entrypoint-initdb.d
    restart: always

  app:
    build: ./
    ports:
      - 8080:8080
    command: npm run start:dev
    depends_on:
      - mysql-server
    links:
      - mysql-server:db
    restart: always    